const crypto=require("crypto");
const PRODUCTS={template_pack:"MicroTools Hub Template Pack",lifetime_pro:"InvoiceForge Lifetime Pro"};
function valid(product,exp,sig){
  const secret=process.env.FULFILLMENT_SIGNING_SECRET;
  if(!secret)return false;
  const payload=product+"."+exp;
  const expected=crypto.createHmac("sha256",secret).update(payload).digest("hex");
  if(typeof sig!=="string"||sig.length!==expected.length)return false;
  return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(sig));
}
const STYLE=`<style>
:root{color-scheme:light}*{box-sizing:border-box}body{font:16px/1.6 system-ui,-apple-system,sans-serif;max-width:900px;margin:28px auto;padding:20px;color:#172033;background:#f7f8fb}header{padding:26px;background:#111827;color:white;border-radius:16px;margin-bottom:20px}header p{color:#d0d5dd}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.toolbar button{padding:10px 14px;border:1px solid #cbd5e1;border-radius:9px;background:white;font:inherit;font-weight:700;cursor:pointer}.sheet{background:white;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin:16px 0;break-inside:avoid}.sheet h2{margin-top:0;font-size:21px}.subject{color:#475569;font-size:14px}.placeholder{background:#f1f5f9;border-radius:4px;padding:0 3px}li{margin:7px 0}small,footer{color:#64748b}.checklist li{list-style:"☐  "}.note{border-left:4px solid #635bff;padding:10px 14px;background:#f1f0ff}footer{padding:18px 0}@media print{body{background:white;max-width:none;margin:0;padding:0}.toolbar{display:none}header,.sheet{break-inside:avoid}header{color:#111;background:#f1f5f9;border:1px solid #ddd}header p{color:#333}.sheet{border:1px solid #bbb;box-shadow:none}}
</style>`;
function shell(title,intro,content){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title}</title>${STYLE}</head><body><header><p>INVOICEFORGE · PURCHASED RESOURCE</p><h1>${title}</h1><p>${intro}</p></header><div class="toolbar"><button onclick="window.print()">Print / Save as PDF</button><button onclick="navigator.clipboard.writeText(document.querySelector('main').innerText).then(()=>this.textContent='Copied page text').catch(()=>alert('Select and copy the text manually.'))">Copy page text</button></div><main>${content}</main><footer>Keep this resource for your business workflow. Adapt the examples to your agreement, local requirements, and client relationship.</footer></body></html>`;}
function sheet(title,body){return `<section class="sheet"><h2>${title}</h2>${body}</section>`;}
function templatePack(){
 const items=[
  ["1. Payment request",'<p class="subject">Subject: Invoice [INVOICE NUMBER] — payment due [DUE DATE]</p><p>Hello [CLIENT NAME],</p><p>Attached is invoice [INVOICE NUMBER] for [PROJECT / SERVICE], totaling [AMOUNT] and due on [DUE DATE]. Please use [PAYMENT METHOD / LINK] and include the invoice number as the reference.</p><p>Thank you,<br>[YOUR NAME] · [BUSINESS NAME]</p>'],
  ["2. Friendly payment reminder",'<p class="subject">Subject: Friendly reminder: invoice [INVOICE NUMBER]</p><p>Hi [CLIENT NAME],</p><p>A quick reminder that invoice [INVOICE NUMBER] for [AMOUNT] was due on [DUE DATE]. If payment has already been sent, thank you — please disregard this note. Otherwise, could you let me know when we can expect it?</p><p>Best,<br>[YOUR NAME]</p>'],
  ["3. Past-due follow-up",'<p class="subject">Subject: Follow-up on overdue invoice [INVOICE NUMBER]</p><p>Hello [CLIENT NAME],</p><p>Our records show [AMOUNT] on invoice [INVOICE NUMBER] remains outstanding after the [DUE DATE] due date. Please confirm the payment status or contact me by [RESPONSE DATE] if there is an issue to resolve.</p><p>This is a request to coordinate next steps; any fees or remedies depend on our agreement and applicable law.</p><p>Regards,<br>[YOUR NAME]</p>'],
  ["4. Project quote",'<p><strong>Prepared for:</strong> [CLIENT / COMPANY]<br><strong>Prepared by:</strong> [BUSINESS NAME]<br><strong>Project:</strong> [PROJECT NAME]<br><strong>Quote valid until:</strong> [DATE]</p><p><strong>Goals and scope:</strong> [DESCRIBE DELIVERABLES AND WHAT IS NOT INCLUDED]</p><p><strong>Timeline:</strong> [MILESTONES / ESTIMATED DATES]</p><p><strong>Investment:</strong> [AMOUNT] · [DEPOSIT / MILESTONE PAYMENT TERMS]</p><p><strong>Assumptions:</strong> [CLIENT INPUTS, REVISION LIMITS, DEPENDENCIES]</p><p>Approval: [CLIENT NAME / DATE]</p>'],
  ["5. Proposal follow-up",'<p class="subject">Subject: Checking in on [PROJECT NAME] proposal</p><p>Hi [CLIENT NAME],</p><p>I wanted to check whether you had questions about the proposal sent on [DATE]. I’m happy to clarify the scope, timing, or budget. If priorities have changed, that’s fine too — a quick update will help me plan.</p><p>Thanks,<br>[YOUR NAME]</p>'],
  ["6. Project kickoff",'<p class="subject">Subject: Kickoff details for [PROJECT NAME]</p><p>Hello [CLIENT NAME],</p><p>To get started, please confirm: (1) primary contact and approver, (2) final scope and deliverables, (3) assets or access needed, (4) review turnaround, (5) milestones and payment schedule, and (6) the best channel for updates.</p><p>Our first milestone is [MILESTONE] targeted for [DATE], assuming required inputs arrive by [DATE].</p><p>Best,<br>[YOUR NAME]</p>'],
  ["7. Project status update",'<p class="subject">Subject: [PROJECT NAME] — progress update for [DATE]</p><p><strong>Completed:</strong> [WORK FINISHED]<br><strong>In progress:</strong> [CURRENT WORK]<br><strong>Next:</strong> [NEXT ACTION + OWNER]<br><strong>Decision needed:</strong> [QUESTION / DEADLINE]<br><strong>Timeline or budget change:</strong> [NONE / DETAILS]</p><p>Please send any feedback by [DATE] to keep the next milestone on schedule.</p>'],
  ["8. Scope-change request",'<p class="subject">Subject: Approval needed — change to [PROJECT NAME]</p><p>Requested change: [DESCRIPTION]</p><p>Why it is needed: [REASON]</p><p>Effect on deliverables: [IMPACT]</p><p>Additional fee or credit: [AMOUNT / NO CHANGE]</p><p>Schedule impact: [NEW DATE / NO CHANGE]</p><p>Please reply with written approval before this change begins. Until approval, the original agreed scope remains the working plan.</p>'],
  ["9. Delivery and handoff",'<p class="subject">Subject: [PROJECT NAME] deliverables and handoff</p><p>Hi [CLIENT NAME],</p><p>The agreed deliverables are ready: [LINK / LOCATION]. Included: [LIST]. To review, please [REVIEW STEPS] and send one consolidated list of any in-scope changes by [DATE].</p><p>Ongoing maintenance, support, or additional work is [INCLUDED / OUTSIDE SCOPE — DESCRIBE]. Thank you for the collaboration.</p>'],
  ["10. Invoice clarification",'<p class="subject">Subject: Re: question about invoice [INVOICE NUMBER]</p><p>Hi [CLIENT NAME],</p><p>Thanks for checking. The line [LINE ITEM] covers [PLAIN-LANGUAGE EXPLANATION] under [QUOTE / AGREEMENT / MILESTONE]. I’ve attached [SUPPORTING DETAIL] for reference. If I’ve misunderstood your question, please point me to the specific item and I’ll review it.</p><p>Best,<br>[YOUR NAME]</p>'],
  ["11. Client thank-you",'<p class="subject">Subject: Thank you for working with [BUSINESS NAME]</p><p>Hi [CLIENT NAME],</p><p>Thank you for trusting me with [PROJECT / SERVICE]. I appreciated working with you. If there is a next phase or a related need, feel free to reach out. Your feedback on the process is welcome.</p><p>Warmly,<br>[YOUR NAME]</p>'],
  ["12. Monthly admin checklist",'<ul class="checklist"><li>Match sent invoices to payment records.</li><li>Follow up on overdue balances professionally.</li><li>Save receipts and categorize business expenses.</li><li>Review upcoming renewals, subscriptions, and tax dates.</li><li>Back up invoices, agreements, and project approvals.</li><li>Review unpaid work and upcoming cash commitments.</li><li>Confirm any tax/accounting treatment with a qualified local professional.</li></ul>']
 ];
 return shell("Business Template Pack","12 editable client communication and admin templates. Replace bracketed prompts, review for your situation, then copy into your email or document app.",items.map(x=>sheet(x[0],x[1])).join(""));
}
function lifetimePro(){
 const items=[
  ["Start here: your repeatable invoice workflow",'<ol><li>Agree on scope, deliverables, due dates, revision limits, and payment milestones before work starts.</li><li>Open InvoiceForge and enter your business and client details.</li><li>Use a unique invoice number; include issue date, due date, item descriptions, quantities, rates, tax and discount where applicable.</li><li>Check totals and currency, add clear payment instructions, then use Print / Save as PDF.</li><li>Send the PDF using your normal email or invoicing process; record the sent date and due date in your own tracker.</li><li>Reconcile payment against your bank or payment-provider records. Keep copies securely.</li></ol><p class="note">The current web app creates invoices in your browser. It does not store invoices, send email, process your clients’ invoice payments, or provide cloud account syncing.</p>'],
  ["Invoice quality-control checklist",'<ul class="checklist"><li>Correct legal / trading name and contact details.</li><li>Correct client billing name and address details as required.</li><li>Unique invoice number and issue date.</li><li>Clear line-item descriptions, quantities, and rates.</li><li>Correct arithmetic, tax treatment, discount, and currency.</li><li>Due date and agreed payment instructions.</li><li>Relevant purchase-order or project reference.</li><li>Terms consistent with the signed agreement and local law.</li><li>PDF opens and is readable on desktop and mobile.</li><li>Copy saved to a secure folder and entry added to your own tracker.</li></ul>'],
  ["Quote-to-cash tracker",'<p>Use a spreadsheet with one row per invoice and these columns:</p><p><strong>Client | Project | Quote approved | Invoice no. | Issue date | Due date | Total | Currency | Status | Last follow-up | Paid date | Receipt/reference | Next action</strong></p><p>Suggested status values: Draft · Sent · Part-paid · Paid · Overdue · Disputed · Cancelled. Update the tracker after sending, follow-up, and reconciliation. Do not store card details, passwords, or unnecessary sensitive client data in it.</p>'],
  ["Quote and scope template",'<p><strong>Objective:</strong> [CLIENT GOAL]<br><strong>Deliverables:</strong> [SPECIFIC OUTPUTS]<br><strong>Exclusions:</strong> [NOT INCLUDED]<br><strong>Client responsibilities:</strong> [ASSETS / ACCESS / APPROVALS]<br><strong>Milestones:</strong> [DATES AND ACCEPTANCE CRITERIA]<br><strong>Fee and payment schedule:</strong> [AMOUNTS / DUE TRIGGERS]<br><strong>Revisions:</strong> [NUMBER / BOUNDARIES]<br><strong>Change control:</strong> Additional work requires a written description of fee and schedule impact and approval before starting.<br><strong>Quote expiry:</strong> [DATE]</p>'],
  ["Deposit / milestone invoice email",'<p class="subject">Subject: [PROJECT] — invoice for [MILESTONE]</p><p>Hi [CLIENT NAME],</p><p>As agreed in the project schedule, attached is invoice [NUMBER] for [DEPOSIT / MILESTONE], totaling [AMOUNT] and due [DATE]. The related milestone is [DESCRIPTION]. Please use [PAYMENT INSTRUCTIONS] and reference [NUMBER].</p><p>Thank you,<br>[NAME]</p>'],
  ["Payment follow-up sequence",'<p><strong>Before due date:</strong> Send a brief courtesy note with the invoice attached and payment details.</p><p><strong>1–3 days after due date:</strong> Send a friendly reminder; allow for bank processing and possible crossed payments.</p><p><strong>7–14 days overdue:</strong> Ask for a status and whether any issue needs resolving; refer to the agreed terms.</p><p><strong>Further delay:</strong> Review the contract and local rules, keep communications factual, and consider professional advice before applying fees, suspending work, or pursuing collection.</p><p class="note">These are general workflow suggestions, not legal advice. Adjust timing to your agreement, client relationship, and applicable law.</p>'],
  ["Client onboarding checklist",'<ul class="checklist"><li>Confirm client billing details and billing contact.</li><li>Document scope, deliverables, exclusions, and acceptance criteria.</li><li>Agree rates, taxes if applicable, deposit, milestones, and due dates.</li><li>Confirm revision limits, communication channel, and response times.</li><li>Collect only necessary assets and permissions securely.</li><li>Confirm who can approve changes and invoices.</li><li>Store signed agreement and approvals in a secure location.</li></ul>'],
  ["Weekly project update",'<p><strong>Project / reporting period:</strong> [NAME / DATES]<br><strong>Overall status:</strong> [On track / At risk / Blocked]<br><strong>Completed this week:</strong> [ITEMS]<br><strong>Next week:</strong> [ITEMS + OWNERS]<br><strong>Client input needed:</strong> [WHAT / BY WHEN]<br><strong>Risks or blockers:</strong> [DETAILS / MITIGATION]<br><strong>Schedule / budget:</strong> [CURRENT POSITION / CHANGES]</p>'],
  ["Scope change approval",'<p><strong>Change requested:</strong> [DETAIL]<br><strong>Reason:</strong> [WHY]<br><strong>Deliverable impact:</strong> [WHAT CHANGES]<br><strong>Fee impact:</strong> [AMOUNT / CURRENCY]<br><strong>Timeline impact:</strong> [DATES]<br><strong>Dependencies:</strong> [CLIENT INPUT / THIRD PARTY]</p><p>Please approve in writing before work begins. Keep the original agreed scope and this approval together in your project records.</p>'],
  ["Project handoff and acceptance",'<p><strong>Deliverables:</strong> [LIST + LOCATION]<br><strong>How to use / access:</strong> [INSTRUCTIONS]<br><strong>Known limitations:</strong> [DETAILS]<br><strong>Review / acceptance deadline:</strong> [DATE FROM AGREEMENT]<br><strong>Included support:</strong> [SCOPE AND PERIOD]<br><strong>Out-of-scope support:</strong> [PROCESS / RATE IF AGREED]</p><p>Thank you for the opportunity to work together. Please keep this handoff with your project records.</p>'],
  ["Monthly business admin routine",'<ul class="checklist"><li>Reconcile invoice totals and receipts with actual payments.</li><li>Review overdue invoices and schedule appropriate follow-ups.</li><li>Save expense receipts and categorize transactions.</li><li>Review subscriptions, recurring costs, and cash commitments.</li><li>Back up contracts, approvals, deliverables, and invoice PDFs.</li><li>Review upcoming deadlines and estimated tax obligations.</li><li>Check pricing and project profitability using actual hours and costs.</li><li>Ask a qualified local accountant about tax or record-retention questions.</li></ul>'],
  ["Simple pricing sanity check",'<p>Estimate a project price using:</p><p><strong>Estimated hours × target hourly rate + direct project costs + contingency</strong></p><p>Then compare the result with the client value, scope uncertainty, market positioning, and your capacity. For a fixed-price project, define assumptions and change control. For a target effective rate, calculate: <strong>(project revenue − direct project costs) ÷ actual hours</strong>. This is a planning aid, not tax or financial advice.</p>'],
  ["Recordkeeping and privacy basics",'<ul><li>Store invoice PDFs, agreements, and receipts in a backed-up, access-controlled location.</li><li>Use consistent filenames, such as <em>YYYY-MM-DD_Client_Invoice-123.pdf</em>.</li><li>Keep payment records from your actual provider or bank; an invoice marked paid is not proof of settlement.</li><li>Collect only client information you need and share files only with intended recipients.</li><li>Use retention periods and tax-record practices appropriate to your jurisdiction.</li><li>Never place payment-card data or account passwords in invoice notes.</li></ul>']
 ];
 return shell("InvoiceForge Lifetime Pro Toolkit","A practical invoice workflow, client communication templates, project controls, and monthly admin checklists to help run a small service business.",items.map(x=>sheet(x[0],x[1])).join(""));
}
function page(product){return product==="template_pack"?templatePack():lifetimePro();}
module.exports=async(req,res)=>{
  const{product,exp,sig}=req.query||{},n=Number(exp);
  if(!PRODUCTS[product]||!Number.isSafeInteger(n)||n<Math.floor(Date.now()/1000)||!valid(product,n,String(sig)))return res.status(403).send("Download link expired or invalid.");
  res.setHeader("Content-Type","text/html; charset=utf-8");
  res.setHeader("Cache-Control","private, no-store");
  res.status(200).send(page(product));
};